---
  
- name: Install Openvpn
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - firewalld
    - openvpn

- name: Liberar as portas no SELINUX
  vars:
    protocols:
      - tcp
      - udp
  with_nested:
    - "{{ user_openvpn }}"
    - "{{ protocols }}"
  community.general.seport:
    ports: "{{ item.0.port }}"
    proto: "{{ item.1 }}"
    setype: openvpn_port_t
    state: present
