---
- name: GENERATE CERTIFICATE
  hosts: all
  gather_facts: false
  strategy: linear
  become: true
  vars:
    secret_ca_passphrase: 1q2w3e4r
    dest_diretorio: /etc/openvpn/ssl
    ip_local: 192.168.0.132
    interface_local: wlan0

    user_openvpn:
      - {
        name: laurobmb@gmail.com,
        port: 1194,
        network: 10.8.201.0,
        mask: 255.255.255.240,
        ip_externo: 125.172.114.19,
        interface_tunel: tun0,
        permit_ranges: [
          "192.168.0.5-192.168.0.254",
          "192.168.1.5-192.168.1.254",
        ],
        routes: [
          "192.168.0.0 255.255.255.0",
          "192.168.1.0 255.255.255.0",
        ]
      }

      - {
        name: lagomes@redhat.com,
        port: 1195,
        network: 10.8.202.0,
        mask: 255.255.255.240,
        ip_externo: 125.172.114.19,
        interface_tunel: tun1,
        permit_ranges: [
          "192.168.2.5-192.168.2.254",
          "192.168.3.5-192.168.3.254",
          "192.168.4.5-192.168.4.254",
          "192.168.5.5-192.168.5.254",
        ],
        routes: [
          "192.168.0.0 255.255.255.0",
          "192.168.3.0 255.255.255.0",
          "192.168.5.0 255.255.255.0",
          "192.168.6.0 255.255.255.0",
        ]
      }

      - {
        name: lauro@hotmail.com,
        port: 1196,
        network: 10.8.203.0,
        mask: 255.255.255.240,
        ip_externo: 125.172.114.19,
        interface_tunel: tun2,
        permit_ranges: [
          "192.168.6.5-192.168.6.254",
          "192.168.7.5-192.168.7.254",
          "192.168.8.5-192.168.8.254"
        ],
        routes: [
          "192.168.0.0 255.255.255.0",
          "192.168.4.0 255.255.255.0",
          "192.168.5.0 255.255.255.0",
        ]
      }

  pre_tasks:

    - name: Coletar o ansible_distribution
      ansible.builtin.setup:
        filter: ansible_distribution

    - name: Debug
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Install packages raspberry
      ansible.builtin.import_role:
        name: packages_raspberry
      when: ansible_distribution == "raspberry"

    - name: Install packages fedora
      ansible.builtin.import_role:
        name: packages_fedora
      when: ansible_distribution == "Fedora"

    - name: Create directory
      ansible.builtin.file:
        path: "{{ dest_diretorio }}"
        state: directory
        recurse: true
        owner: root
        group: root

  roles:
    - role: certificate

  tasks:

    - name: Enable router
      ansible.builtin.import_tasks: enable_router.yml

    - name: Edit Iptables
      ansible.builtin.import_tasks: iptables.yml

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        name: "openvpn-server@server-{{ item.name.split('@')[0] | lower | regex_replace('[.|_]', '') }}"
        enabled: true
      loop: "{{ user_openvpn }}"
