---
- name: GENERATE CERTIFICATE
  hosts: all
  gather_facts: false
  strategy: linear
  become: true
  vars:
    secret_ca_passphrase: 1q2w3e4r
    dest_diretorio: /etc/openvpn/ssl
    ip_local: 192.168.0.132
    user_openvpn:
      - { name: lagomes@gmail.com, port: 1194, network: 10.8.201.0, mask: 255.255.255.240, ip_externo: 45.171.124.18 }
      - { name: liz@gmail.com,     port: 1195, network: 10.8.202.0, mask: 255.255.255.240, ip_externo: 45.171.124.18 }
#      - { name: camila@gmail.com,  port: 1196, network: 10.8.203.0, mask: 255.255.255.240, ip_externo: 45.171.124.18 }
#      - { name: peguel@gmail.com,  port: 1197, network: 10.8.204.0, mask: 255.255.255.240, ip_externo: 45.171.124.18 }

#  pre_tasks:
#    - name: Atualizar a lista de pacotes APT
#      ansible.builtin.apt:
#        update_cache: true
#
#    - name: Install Openvpn
#      ansible.builtin.apt:
#        name: openvpn
#        state: present
#
#    - name: Create directory
#      ansible.builtin.file:
#        path: "{{ dest_diretorio }}"
#        state: directory
#        recurse: true
#        owner: root
#        group: root

  roles:
    - role: certificate
