---

- name: Create TLS from server
  ansible.builtin.import_tasks: create_tls.yml

- name: Create DH from server
  ansible.builtin.import_tasks: create_dh.yml

- name: Create CA
  ansible.builtin.import_tasks: create_ca.yml

- name: Create server
  ansible.builtin.import_tasks: create_server.yml

- name: Create client certificates
  ansible.builtin.import_tasks: create_clients.yml

- name: Create files
  ansible.builtin.import_tasks: create_files.yml
