---
- name: Generate certificate x509
  hosts: localhost
  tasks:

  - name: Generate keyfile
    community.crypto.openssl_privatekey:
      path: conectado.local.pem
      size: 2048

  - name: Create CSR
    community.crypto.openssl_csr:
      path: conectado.local.csr
      privatekey_path: conectado.local.pem
      country_name: BR
      organization_name: conectado
      email_address: lagomes@ansible.com
      common_name: '*.conectado.local'

  - name: Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: conectado.local.crt
      privatekey_path: conectado.local.pem
      csr_path: conectado.local.csr
      provider: selfsigned
