---
version: 3

build_arg_defaults:
    ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--ignore-certs"

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest'

options:
    package_manager_path: /usr/bin/microdnf

dependencies:
  system: files/bindep.txt
  galaxy: files/requirements.yml
  python: files/requirements.txt

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
    #prepend_base:
    #- COPY _build/configs/rootCA.crt /usr/share/pki/ca-trust-source/anchors
    #- RUN update-ca-trust
    prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    prepend_final: |
      RUN whoami
      RUN cat /etc/os-release
      RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      RUN /usr/bin/microdnf repolist
      RUN /usr/bin/microdnf install openvpn
      RUN /usr/bin/microdnf clean all
    append_final: |
      RUN curl -o /usr/bin/butane -L -O https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane

